# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\x12\rserialization\"\xe4\x01\n\x06Object\x12\x14\n\x07integer\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x15\n\x08\x66loating\x18\x02 \x01(\x02H\x01\x88\x01\x01\x12\x10\n\x03str\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x0c\n\x04list\x18\x04 \x03(\x03\x12\x39\n\ndictionary\x18\x05 \x03(\x0b\x32%.serialization.Object.DictionaryEntry\x1a\x31\n\x0f\x44ictionaryEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\n\n\x08_integerB\x0b\n\t_floatingB\x06\n\x04_strb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBJECT_DICTIONARYENTRY._options = None
  _OBJECT_DICTIONARYENTRY._serialized_options = b'8\001'
  _OBJECT._serialized_start=32
  _OBJECT._serialized_end=260
  _OBJECT_DICTIONARYENTRY._serialized_start=178
  _OBJECT_DICTIONARYENTRY._serialized_end=227
# @@protoc_insertion_point(module_scope)
